### ISSUE TITLE
Pausing the rotation also pauses camera movement in the 4th axis and higher

### ISSUE THREAD

**Issue by galoomba1** [Reinhardt-C/Reintope#1]
How to reproduce:
- Load a 4D or higher polytope
- Pause the rotation
- Move the camera sliders w, x5, ...

The image does not update until you unpause the rotation.

**Comment by Reinhardt-C** [comment]
Resolved

**Comment by galoomba1** [comment]
Not fixed. Now moving the W slider makes it rotate, and sliders 5+ still don't work.
